[package]
name = "automake"
version = "1.17"
description = "description"
license = "MIT"
arch="*"
dependencies = []
maintainer = "Marcus Andersson <marcus@unifun.se>"
source_location="https://ftp.gnu.org/gnu/automake/automake-1.17.tar.xz"

build = [
    "BUILD",
]
