[package]
name = "iproute2"
version = "6.10.0"
description = "description"
license = "MIT"
arch="*"
dependencies = []
maintainer = "Marcus Andersson <marcus@unifun.se>"
source_location="https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-6.10.0.tar.xz"

build = [
    "BUILD",
]
