[package]
name = "mpc"
version = "1.3.1"
description = "contains a library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result"
license = "MIT"
arch="*"
dependencies = []
maintainer = "Marcus Andersson <marcus@unifun.se>"
source_location="https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz"

build = [
    "BUILD",
]
