[package]
name = "autoconf"
version = "2.72"
description = "description"
license = "MIT"
arch="*"
dependencies = []
maintainer = "Marcus Andersson <marcus@unifun.se>"
source_location="https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"

build = [
    "BUILD",
]
