[package]
name = "libelf"
version = "0.191"
description = "description"
license = "MIT"
arch="*"
dependencies = []
maintainer = "Marcus Andersson <marcus@unifun.se>"
source_location="https://sourceware.org/ftp/elfutils/0.191/elfutils-0.191.tar.bz2"

build = [
    "BUILD",
]
