[package]
name = "bison"
version = "3.8.2"
description = "A general-purpose parser generator."
license = "MIT"
arch = "*"
dependencies = []
maintainer = "Marcus Andersson <marcus@unifun.se>"
source_location = "https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz"

build = [
    "BUILD",
]
