[package]
name = "iana-etc"
version = "20240806"
description = "stuff from iana"
license = "MIT"
arch="*"
dependencies = []
maintainer = "Marcus Andersson <marcus@unifun.se>"
source_location="https://github.com/Mic92/iana-etc/releases/download/20240806/iana-etc-20240806.tar.gz"

build = [
    "BUILD",
]
