[package]
name = "zlib"
version = "1.3.1"
description = "The Zlib package contains compression and decompression routines used by some programs."
license = "MIT"
arch="*"
dependencies = []
maintainer = "Marcus Andersson <marcus@unifun.se>"
source_location="https://zlib.net/fossils/zlib-1.3.1.tar.gz"

build = [
    "BUILD",
]
